name: Daily Update

on:
  schedule:
    - cron: '00 5 * * *'

  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.16
    - run: npm install
    - run: npm install download
    - run: npm install js-joda
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true

    - name: Update README
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |-
        node pizzaupdate.js
        cat README.md
        node selfpromoupdate.js
        cat README.md

    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.name "Slice-bot"
        git add -A
        git commit -m "Updated Pizza Joint of the Day" || exit 0
        git push
